config/routes.rb
OneCase::Application.routes.draw do
  get "home/index"
  resources :organizations
  root :to => 'home#index'
end

app/models/case.rb
class Case
  include Mongoid::Document
  include Mongoid::Timestamps
  
  mount_uploader :image, ImageUploader

  field :title, :type => String
  field :first_name, :type => String
  field :middle_name, :type => String
  field :last_name, :type => String
  field :initials, :type => String
  field :street_name, :type => String
  field :building_no, :type => String
  field :city, :type => String
  field :telephone, :type => String
  field :mobile, :type => String
  field :classification, :type => String
  field :payment_type, :type => String
  field :description, :type => String
  field :requirements, :type => String
  field :amount_required, :type => Float
  field :current_amount, :type => Float
  field :facebook_page, :type => String
  field :twitter_page, :type => String
  field :due_date, :type => DateTime
  field :done, :type => Boolean
  field :ngo_contact_person, :type => String
  field :ngo_contact_person_phone, :type => String
  field :video_url, :type => String

  def self.current
    self.first
  end

  def amount_remaining
    amount_required - current_amount
  end
end

app/models/organization.rb
class Organization
  include Mongoid::Document
  include Mongoid::Timestamps

  mount_uploader :image, ImageUploader

  field :name, localize: true
  field :slug
  field :description
  field :extra_description
  field :fund_raised, type: Integer, default: 0
  field :donators_count, type: Integer, default: 0
  field :days_count, type: Integer, default: 0
  field :registration_number
  field :address
  field :phone_numbers
  field :bank_account_number

  validates_uniqueness_of :name
  validates_presence_of :name, :description, :address, :phone_numbers, :bank_account_number

  has_many :cases

  before_create :slugify

  def slugify
    self.slug = self.name.gsub /\s+/, '-'
  end

  def to_param
    self.slug
  end
end

app/models/subscriber.rb
class Subscriber
  include Mongoid::Document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @case = Case.current
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.page(params[:page]).per(params[:per])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.first(conditions: { slug: params[:id] })

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def amount_donated_class(_case)
    "span25th"
  end

  def amount_remaining_class(_case)
    "span25th"
  end

  def google_analytics_js
    if ['production', 'staging'].include?(Rails.env)
      "<script type=\"text/javascript\">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-32396686-1']);
        _gaq.push(['_setDomainName', '7alawa7da.com']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
      </script>"
    end
  end

  def meta_title
    if params[:controller] == 'organizations' && params[:action] == 'show'
      "#{@organization.name} @7alaWa7da"
    elsif params[:controller] == 'cases' && params[:action] == 'show'
      "#{@case.name} @7alaWa7da"
    else
     '7alaWa7da'
    end
  end

  def meta_description
    if params[:controller] == 'organizations' && params[:action] == 'show'
      "#{@organization.description} @7alaWa7da"
    elsif params[:controller] == 'cases' && params[:action] == 'show'
      "#{@case.description} @7alaWa7da"
    else
     '7alaWa7da'
    end
  end

  def meta_image
    url = nil
    return ''
  end

  def meta_canonical_url
    request.url
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="span6 case">
      <p><a href="#" class="title-small">زكاة مال</a> : <a href="#" class="title-small"> زواج</a></p>
      <h1><a href="#">إتبرع لإنقاذ حياة محمد حسني مبارك من المرض</a></h1>
      <p>حسني مبارك يعاني من أمراض عديدة مجهولة النوع والمصدر ويوجد بعض التشككات إنه حوار بس على رأي غسان مطر؛ اعمل الصح!</p>
      <div class="case actions">
        <a href="#" class="btn btn-primary btn-large">اتبرع دلوقت</a>&nbsp;&nbsp;
        <a href="#">تفاصيل أكتر عن الحالة  &raquo;</a>
      </div>
    </div><!--end span6-->
    <div class="span5 offset1">
      <p class="title-small">الوقت المتبقى علشان تتبرع</p>
      <div class="time">
        <span class="day">02</span>
        <span class="hour">19</span>
        <span class="min">30</span>
        <span class="sec">02</span>
      </div>

      <p class="title-small">الفلوس المطلوبه</p>
      <div class="progress">
        <div class="bar" style="width: 60%;"></div>
      </div>


      <div class="span2 money">
        <p>جمعنا <br /> <strong>145,000</strong> جنيه</p>
      </div>
      <div class="span2 money">
        <p>فاضل <br /> <strong>135,000</strong> جنيه</p>
      </div>

    </div><!--end span5-->


  </div><!--end row-->

  <div class="row media-share">
    <div class="span9"><p class="pull-left">ساعدنا بنشر الفيديو</p></div> 
    <div class="span3"><img src="../images/socia-share.png"  /></div>
  </div>

  <div class="row">
    <div class="span12">
      <div class="media-show">
        <img src="../images/dumm/video.jpg" width="854" height="510" /></div>
    </div>
  </div><!--end row-->

</div><!--end container-->

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="title" content="<%= meta_title %>">
    <meta name="description" content="<%= meta_description %>">
    <meta name="author" content="7alaWa7da">
    <meta name="keywords" content="7alaWa7da">
    <link rel="canonical" href="<%= meta_canonical_url %>" />
    <meta name="copyright" content="(c) Copyright 2012, 7alaWa7da. All Right reserved.">

    <link href="/stylesheets/bootstrap2.css" rel="stylesheet"  />
    <link href="/stylesheets/styles.css" rel="stylesheet"  />
    <title>Home - 7alaWa7da</title>
  </head>

  <body>

    <div class="header">
      <div class="container">
        <div class="row">
          <div class="span1">
            <h1><a href="/" class="logo">حالة واحدة</a></h1>
          </div>
          <div class="span5">
            <ul class="nav nav-pills">
              <li><a href="#"><%= t(:about_us) %></a></li>
              <li><a href="#"><%= t(:previous_cases) %></a></li>
              <li class="<%= params[:controller] == 'organizations' && params[:action] == 'index' ?
                'active' : '' %>">
                <a href="#"><%= t(:reg_orgs) %></a>
              </li>
            </ul>
          </div>
          <div class="span1">
            <a href="http://www.facebook.com/7alaWa7da" class="social facebook" title="Facebook">Facebook</a>
            <a href="#" class="social google" title="Google plus">Google plus</a>
            <a href="https://twitter.com/#!/7alaWa7da" class="social twitter" title="Twitter">Twitter</a>
          </div>
          <div class="span4 search">
            <p>إشترك معانا عشان توصلك آخر أخبار الحالات</p>
            <form class="form-inline">
              <input type="text" placeholder="بريدك الالكترونى" />
              <button class="btn btn-primary">اشترك</button>
            </form>
          </div>
        </div>
    
      </div>
    </div><!--end header-->


    <div class="content">
      <div class="container">
        <%= yield %>
      </div>
    </div><!--end contet-->


    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="span8 menu">
            <a href="#">الحالة السابقة</a>
            <a href="#">الحالة السابقة</a>
            <a href="#">الحالة السابقة</a>
          </div>
          <div class="span4 search">
            <p>إشترك معانا عشان توصلك آخر أخبار الحالات</p>
            <form class="form-inline">
              <input type="text" placeholder="بريدك الالكترونى" />
              <button class="btn btn-primary">اشترك</button>
            </form>
          </div>
        </div>
      </div>
    </div><!--end footer-->

    <%= raw google_analytics_js %>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization, html: { class: 'form-horizontal' }) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="control-group">
      <%= f.input :name %>
    </div>
    <div class="control-group">
      <%= f.input :description, as: :text, input_html: { class: 'input-xlargs', rows: 5 } %>
    </div>
    <div class="control-group">
      <%= f.input :address %>
    </div>
    <div class="control-group">
      <%= f.input :phone_numbers %>
    </div>
    <div class="control-group">
      <%= f.input :bank_account_number %>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Save changes</button>
      <button class="btn">Cancel</button>
    </div>
  </fieldset>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<div class="page-header">
  <h1><%= t(:ngos_title) %></h1>
</div>

<div class="row">
<% @organizations.each do |org| %>
  <div class="span5 ngo-block">
    <div class="row">
      <div class="box clearfix">
        <div class="span3 ngo-logo">
          <img src="../images/dumm/ngo-logo.png">
        </div>
        <div class="span2 stats">
          <p><span><%= org.cases.count %></span> <%= t(:case) %></p>
          <p><span><%= number_with_delimiter(org.fund_raised) %></span> <%= t(:pound) %></p>
          <p><span><%= org.donators_count %></span> <%= t(:donators) %></p>
        </div>
      </div><!--end box-->
    </div><!--end row-->
    <div class="row">
      <div class="span5 ngo-info">
        <h3><%= org.name %></h3>
        <p><%= org.description %></p>
        <%= link_to t(:more_details), organization_path(org), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>
</div>

<div class="row">
  <div class="span12">
    <div class="pagination">
      <%= paginate @organizations %>      
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
<h1><%= t(:new_organization) %></h1>

<%= render 'form' %>

app/views/organizations/show.html.erb
<div class="row">
  <div class="span6 case">
    <!-- <p><a href="#" class="title-small">زكاة مال</a> : <a href="#" class="title-small"> زواج</a></p> -->
    <h3 class="title-medium"><%= @organization.name %></h3>
    <div class="center ngo-logo">
      <img src="../images/dumm/ngo-logo.png">
    </div>
    <p>حسني مبارك يعاني من أمراض عديدة مجهولة النوع والمصدر ويوجد بعض التشككات إنه حوار بس على رأي غسان مطر؛ اعمل الصح!</p>
    <p>حسني مبارك يعاني من أمراض عديدة مجهولة النوع والمصدر ويوجد بعض التشككات إنه حوار بس على رأي غسان مطر؛ اعمل الصح!</p>
    <p>حسني مبارك يعاني من أمراض عديدة مجهولة النوع والمصدر ويوجد بعض التشككات إنه حوار بس على رأي غسان مطر؛ اعمل الصح!</p>
    <p>حسني مبارك يعاني من أمراض عديدة مجهولة النوع والمصدر ويوجد بعض التشككات إنه حوار بس على رأي غسان مطر؛ اعمل الصح!</p>
    <p>حسني مبارك يعاني من أمراض عديدة مجهولة النوع والمصدر ويوجد بعض التشككات إنه حوار بس على رأي غسان مطر؛ اعمل الصح!</p>
  </div><!--end span6-->

  <div class="span5 offset1">
    <div class="old-case-box">
      <h2><%= @organization.fund_raised %> <span><%= t(:pound) %></span></h2>
      <h2><%= @organization.donators_count %> <span><%= t(:donators) %></span></h2>
      <h2><%= @organization.days_count %> <span><%= t(:day) %></span></h2>
    </div>
  </div><!--end span5-->
  <div class="span5 offset1">
    <h3 class="title-medium"><%= t(:organization_details) %></h3>
    <ul class="case-list">
      <li><em><%= t(:reg_number) %>: </em>  <%= @organization.registration_number %></li>
      <li><em><%= t(:address) %>:</em>  <%= @organization.address %></li>
      <li><em><%= t(:phone_numbers) %>:</em> <%= @organization.phone_numbers %></li>
      <li><em><%= t(:bank_account_number) %>:</em>  <%= @organization.bank_account_number %></li>
    </ul>
    <p class="title-small"><%= @organization.extra_description %></p>
  </div>

</div>